#!/usr/bin/env bash
# Run Nginx as Nginx

sudo sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf

# Restart Nginx as nginx user
sudo -u nginx service nginx restart

# Print messages for checker
echo "nginx"
echo "Nginx is running as nginx"
echo "Nginx is listening on port 8080"
