#!/usr/bin/env bash
# Install HAProxy and configure load balancing

apt-get update
apt-get -y install haproxy

# Enable HAProxy on boot
echo "ENABLED=1" >> /etc/default/haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
defaults
    mode http
    balance roundrobin

listen load_balancer
    bind *:80
    server web-01 3.82.240.31:80 check
    server web-02 52.90.245.197:80 check
EOF

# Restart HAProxy
systemctl restart haproxy
