#!/usr/bin/env bash
# Installs and configures Nginx to serve a webpage
# with "Holberton School".

# Update package list and install Nginx
apt-get update -y
apt-get install nginx -y

# Start Nginx using service
service nginx start

# Ensure Nginx starts on boot
echo "service nginx start" >> /etc/rc.local

# Modify the default HTML page
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart Nginx using service
service nginx restart
