#!/usr/bin/env bash
# Commands to install Nginx on Web-Server-01

# Updating Packages before making Installations
apt-get update -y
apt-get install nginx -y

# Configuring the Uncomplicated Firewall (UFW)
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Restarting Nginx
service nginx restart
