#!/usr/bin/env bash
## Bash script to install Nginx and configure a redirection

# Update package lists and install Nginx
apt-get update -y
apt-get install -y nginx

# Create an index.html file with required content
echo "Holberton School" > /var/www/html/index.html

# Configure Nginx to serve the index file and add redirection
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
         
    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
                                                    
# Restart Nginx to apply changes
sudo service nginx restart

