#!/usr/bin/env bash
## Configures Nginx to redirect /redirect_me

echo "server {
    listen 80;
    server_name _;
         
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default

service nginx restart

