#!/usr/bin/env bash
# Configure nginx server to have a custom 404 page
sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

config_file="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name _;
	
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	
	error_page 404 /404.html;

	location / {
	    try_files $uri \$uri/ =404;
	}

	location = /404.html {
	    internal;
	}
}"

echo "$config_file" | sudo tee /etc/nginx/sites-available/default > /dev/null
sudo systemctl restart nginx
