#!/usr/bin/env bash
# Custom 404 error page setup for Nginx

echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
    listen 80;
    server_name _;
         
    location / {
        root /var/www/html;
        index index.html;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
